### PR TITLE
vendor: default version and trapped download failures

### LINKED ISSUE #1418: vendor: branch install encounters untar error
```r
remotes::install_github("rstudio/renv", "bugfix/binary-install-test")
renv:::vendor()
#> * Downloading from GitHub ... FAILED
#> Error in utils::untar(tarfile = tarfile, files = files, list = list, exdir = exdir,  : 
#>   invalid 'tarfile' argument
```

### PR DESCRIPTION
**Pull request by aronatkins**
Traps download failures, as we were attempting to `untar(FALSE)` before. Default the vendor version to the current renv version. Print the version when downloading from GitHub.

This lets me successfully:

```
remotes::install_github("rstudio/renv", "aron-vendor-untar-fix")
renv:::vendor()
```

Feel free to discard/reimplement if the intent was some other interaction with `vendor`.

Fixes #1418

Note: Rooted on https://github.com/rstudio/renv/pull/1407 because that's the change I wanted to use.

### CODE REVIEW

File: R/vendor.R [hunk 1]
```diff
@@ -45,7 +45,7 @@ vendor <- function(version    = NULL,
   }
 
   # get renv sources
-  sources <- sources %||% renv_vendor_sources(version)
+  sources <- sources %||% renv_vendor_sources(version %||% renv_metadata_version())
```
Comment (kevinushey) [inline R/vendor.R:48]: I think this now needs to be a commit SHA rather than a version, now that we're no longer tagging every renv commit. @hadley, what do you think the right approach is? If `version` is NULL, should we just use the SHA associated with the tip of main?

File: R/vendor.R [hunk 2]
```diff
@@ -150,6 +150,9 @@ renv_vendor_imports <- function() {
 renv_vendor_sources <- function(version = renv_metadata_version()) {
 
   tarball <- renv_bootstrap_download_github(version)
```
Comment (kevinushey) [inline R/vendor.R:152]: Maybe we should alter this function so that it either returns a path, or emits an error (instead of FALSE)?

File: R/vendor.R (hunk 1 above)
Comment (aronatkins) [reply R/vendor.R:48]: With these changes, it used e7ec59ff4a92ec15583ac60faa1100f5b490af34 after I had installed this branch with remotes.

```r
renv:::renv_metadata_version()
#> [1] "e7ec59ff4a92ec15583ac60faa1100f5b490af34"
``` 

From the DESCRIPTION:

```
RemoteSha: e7ec59ff4a92ec15583ac60faa1100f5b490af34
```

There is definitely a question about how folks are going to use vendor... will they use vendor to incorporate the code for the version of renv installed locally, or should we require a remote reference? If we have a remote reference, then there is a risk of that remote version needing some alternate strategy for composing all the code.

I don't think that the vendor function can be used with old renv, for example.

I would prefer if `renv:::vendor` lost its inferred argument values; force us to provide values.

File: R/vendor.R (hunk 2 above)
Comment (aronatkins) [reply R/vendor.R:152]: Any option is better than attempting to `untar(FALSE)` 🤣

Do you want to make those changes separately or do you want me to iterate, here?

File: R/vendor.R (hunk 1 above)
Comment (hadley) [reply R/vendor.R:48]: IMO I think we should just default it to `main` — that's likely what you will want most of the time when re-vendoring anyway.  But I'm also fine with leaving version with no default so that you have to pick a sha yourself.

File: R/vendor.R (hunk 2 above)
Comment (hadley) [reply R/vendor.R:152]: I think that's hard to do without changing how `renv_bootstrap_download()` works (along with all other `renv_bootstrap_download_*` functions). It's a bit icky, but I think given that the vendor code is used by only a few people, we should just go with the code in this PR.

File: R/vendor.R (hunk 1 above)
Comment (aronatkins) [reply R/vendor.R]: I've made (version or sources) required.

**Review by kevinushey — APPROVED** [review]

**Review by hadley — APPROVED** [review]
